theme: minima
title: Veronica Olivotto
description: Ciao, I am a researcher passionate about using mix-methods to understand and integrate the lived experiences, perceptions and actions of residents living in coastal and riverine areas affected by flooding and sea level rise into decision making, advocacy strategies and planning for adaptation programs and policies. 
